"use client";

import Link from "next/link";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Dna,
  Upload,
  Brain,
  FileText,
  Calendar,
  TrendingUp,
  Shield,
  Clock,
  Users,
  Star,
  CheckCircle,
  ArrowRight,
} from "lucide-react";

export default function HomePage() {
  const features = [
    {
      icon: Upload,
      title: "DNA Upload & Analysis",
      description:
        "Upload your raw DNA file from 23andMe, MyHeritage, or AncestryDNA. Our advanced parser analyzes key SNPs for dietary insights.",
      color: "text-blue-600",
    },
    {
      icon: Brain,
      title: "AI-Powered Recommendations",
      description:
        "Get personalized dietary advice generated by advanced AI based on your unique genetic profile and health goals.",
      color: "text-purple-600",
    },
    {
      icon: FileText,
      title: "Comprehensive Reports",
      description:
        "Receive detailed PDF reports with your genetic profile, risk assessments, and personalized nutrition plan.",
      color: "text-green-600",
    },
    {
      icon: Calendar,
      title: "Meal Planning",
      description:
        "Generate weekly meal plans with recipes tailored to your genetic profile and dietary preferences.",
      color: "text-orange-600",
    },
    {
      icon: TrendingUp,
      title: "Progress Tracking",
      description:
        "Monitor your health metrics, energy levels, and adherence to your personalized nutrition plan.",
      color: "text-red-600",
    },
    {
      icon: Shield,
      title: "Professional Grade",
      description:
        "Suitable for clinics, nutritionists, and healthcare professionals with multi-client management.",
      color: "text-indigo-600",
    },
  ];

  const stats = [
    { value: "10,000+", label: "Genetic Variants Analyzed" },
    { value: "50+", label: "Dietary Recommendations" },
    { value: "15+", label: "Languages Supported" },
    { value: "99.9%", label: "Analysis Accuracy" },
  ];

  const testimonials = [
    {
      name: "Dr. Sarah Chen",
      role: "Nutritionist",
      content:
        "Elana has revolutionized how I provide personalized nutrition advice to my clients. The genetic insights are incredibly detailed and actionable.",
      rating: 5,
    },
    {
      name: "Michael Rodriguez",
      role: "Health Coach",
      content:
        "The AI-generated meal plans are spot-on for my genetic profile. I've seen significant improvements in my energy levels and overall health.",
      rating: 5,
    },
    {
      name: "Dr. Elena Volkova",
      role: "Medical Geneticist",
      content:
        "As a medical professional, I'm impressed by the scientific accuracy and comprehensive analysis. Perfect for clinical use.",
      rating: 5,
    },
  ];

  return (
    <div className="min-h-screen">
      {/* Hero Section - UBS Style */}
      <section className="ubs-hero ubs-section relative">
        <div className="container relative mx-auto px-4 py-32">
          <div className="mx-auto max-w-4xl text-center">
            <Badge
              className="mb-6 bg-blue-50 text-blue-700 border-blue-200"
              variant="secondary"
            >
              🧬 Advanced Genomics & AI Technology
            </Badge>
            <h1 className="ubs-heading-1 mb-8">
              Personalized Nutrition Through
              <span className="bg-gradient-to-r from-blue-600 to-indigo-600 bg-clip-text text-transparent">
                {" "}
                Genetic Science
              </span>
            </h1>
            <p className="ubs-body text-xl mb-10 max-w-3xl mx-auto leading-relaxed">
              Transform your health with precision nutrition recommendations
              based on your unique genetic profile. Our AI-powered platform
              analyzes your DNA to provide personalized dietary insights backed
              by science.
            </p>
            <div className="flex flex-col gap-4 sm:flex-row sm:justify-center">
              <Link href="/upload">
                <Button
                  size="lg"
                  className="ubs-button-primary text-lg px-10 py-4 rounded-md shadow-sm"
                >
                  <Upload className="mr-2 h-5 w-5" />
                  Analyze Your DNA
                  <ArrowRight className="ml-2 h-5 w-5" />
                </Button>
              </Link>
              <Link href="/demo">
                <Button
                  size="lg"
                  variant="outline"
                  className="ubs-button-outline text-lg px-10 py-4 rounded-md"
                >
                  <Dna className="mr-2 h-5 w-5" />
                  View Sample Report
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Stats Section - UBS Style */}
      <section className="bg-white dark:bg-gray-900 ubs-section-sm border-t border-gray-100 dark:border-gray-800">
        <div className="container mx-auto px-4">
          <div className="grid grid-cols-2 gap-8 md:grid-cols-4">
            {stats.map((stat, index) => (
              <div key={index} className="text-center">
                <div className="ubs-heading-3 text-blue-600 mb-2">
                  {stat.value}
                </div>
                <div className="text-sm text-gray-600 dark:text-gray-400 font-medium uppercase tracking-wide">
                  {stat.label}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section - UBS Style */}
      <section className="ubs-section bg-gray-50 dark:bg-gray-900">
        <div className="container mx-auto px-4">
          <div className="mx-auto max-w-3xl text-center mb-20">
            <h2 className="ubs-heading-2 mb-6">
              Complete Genetic Nutrition Platform
            </h2>
            <p className="ubs-body text-lg leading-relaxed">
              From DNA analysis to personalized meal plans, we provide
              everything you need for optimal nutrition based on your unique
              genetic profile.
            </p>
          </div>

          <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
            {features.map((feature, index) => (
              <Card
                key={index}
                className="ubs-card border-gray-200 dark:border-gray-700 h-full"
              >
                <CardHeader className="pb-4">
                  <div className="inline-flex h-14 w-14 items-center justify-center rounded-lg bg-gray-50 dark:bg-gray-800 mb-4">
                    <feature.icon className={`h-7 w-7 ${feature.color}`} />
                  </div>
                  <CardTitle className="text-xl font-semibold mb-2">
                    {feature.title}
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <CardDescription className="text-base leading-relaxed text-gray-600 dark:text-gray-300">
                    {feature.description}
                  </CardDescription>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works Section - UBS Style */}
      <section className="ubs-section">
        <div className="container mx-auto px-4">
          <div className="mx-auto max-w-3xl text-center mb-20">
            <h2 className="ubs-heading-2 mb-6">How It Works</h2>
            <p className="ubs-body text-lg leading-relaxed">
              Get personalized nutrition recommendations in three simple steps
            </p>
          </div>

          <div className="grid gap-12 md:grid-cols-3">
            <div className="text-center">
              <div className="mx-auto mb-8 flex h-20 w-20 items-center justify-center rounded-full bg-blue-50 dark:bg-blue-900/20 border-2 border-blue-100 dark:border-blue-800">
                <Upload className="h-9 w-9 text-blue-600" />
              </div>
              <h3 className="ubs-heading-3 text-xl mb-4">Upload Your DNA</h3>
              <p className="ubs-body leading-relaxed">
                Upload your raw DNA file from 23andMe, MyHeritage, AncestryDNA,
                or other providers. Our system analyzes key genetic variants
                related to nutrition and metabolism.
              </p>
            </div>

            <div className="text-center">
              <div className="mx-auto mb-8 flex h-20 w-20 items-center justify-center rounded-full bg-purple-50 dark:bg-purple-900/20 border-2 border-purple-100 dark:border-purple-800">
                <Brain className="h-9 w-9 text-purple-600" />
              </div>
              <h3 className="ubs-heading-3 text-xl mb-4">AI Analysis</h3>
              <p className="ubs-body leading-relaxed">
                Our advanced AI analyzes your genetic profile, considering
                factors like fat metabolism, vitamin needs, food intolerances,
                and more to generate personalized recommendations.
              </p>
            </div>

            <div className="text-center">
              <div className="mx-auto mb-8 flex h-20 w-20 items-center justify-center rounded-full bg-green-50 dark:bg-green-900/20 border-2 border-green-100 dark:border-green-800">
                <FileText className="h-9 w-9 text-green-600" />
              </div>
              <h3 className="ubs-heading-3 text-xl mb-4">Get Your Plan</h3>
              <p className="ubs-body leading-relaxed">
                Receive comprehensive dietary recommendations, meal plans,
                supplement suggestions, and lifestyle advice tailored to your
                unique genetic profile.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Testimonials Section - UBS Style */}
      <section className="ubs-section bg-gray-50 dark:bg-gray-900">
        <div className="container mx-auto px-4">
          <div className="mx-auto max-w-3xl text-center mb-20">
            <h2 className="ubs-heading-2 mb-6">
              Trusted by Healthcare Professionals
            </h2>
            <p className="ubs-body text-lg leading-relaxed">
              See what medical professionals and individuals say about our
              genetic nutrition platform
            </p>
          </div>

          <div className="grid gap-8 md:grid-cols-3">
            {testimonials.map((testimonial, index) => (
              <Card
                key={index}
                className="ubs-card h-full bg-white dark:bg-gray-800 border-gray-200 dark:border-gray-700"
              >
                <CardContent className="pt-8">
                  <div className="flex mb-6">
                    {[...Array(testimonial.rating)].map((_, i) => (
                      <Star
                        key={i}
                        className="h-5 w-5 fill-yellow-400 text-yellow-400"
                      />
                    ))}
                  </div>
                  <p className="ubs-body leading-relaxed mb-6 text-gray-700 dark:text-gray-300">
                    "{testimonial.content}"
                  </p>
                  <div className="pt-4 border-t border-gray-100 dark:border-gray-700">
                    <div className="font-semibold text-gray-900 dark:text-white">
                      {testimonial.name}
                    </div>
                    <div className="text-sm text-gray-500 dark:text-gray-400 font-medium">
                      {testimonial.role}
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section - UBS Style */}
      <section className="ubs-section bg-gradient-to-r from-blue-600 via-blue-700 to-indigo-700 text-white relative overflow-hidden">
        <div className="absolute inset-0 bg-black/10"></div>
        <div className="container relative mx-auto px-4 text-center">
          <h2 className="ubs-heading-2 mb-6 text-white">
            Ready to Transform Your Health?
          </h2>
          <p className="text-xl mb-10 opacity-90 max-w-2xl mx-auto leading-relaxed">
            Join thousands of people who have optimized their nutrition with
            precision genetic insights and AI-powered recommendations.
          </p>
          <div className="flex flex-col gap-4 sm:flex-row sm:justify-center">
            <Link href="/upload">
              <Button
                size="lg"
                className="bg-white text-blue-700 hover:bg-gray-50 text-lg px-10 py-4 rounded-md shadow-sm font-medium"
              >
                <Upload className="mr-2 h-5 w-5" />
                Start Your Analysis
              </Button>
            </Link>
            <Link href="/pricing">
              <Button
                size="lg"
                variant="outline"
                className="text-lg px-10 py-4 border-white/30 text-white hover:bg-white/10 rounded-md font-medium"
              >
                View Pricing Options
              </Button>
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}
